In [1]:
import tensorflow

In [2]:
from keras.applications.resnet50 import ResNet50,preprocess_input
from keras.layers import GlobalMaxPooling2D

In [3]:
model=ResNet50(weights='imagenet',include_top=False,input_shape=(224,224,3))
model.trainable=False

In [4]:
model.summary()

Model: "resnet50"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_1 (InputLayer)        [(None, 224, 224, 3)]        0         []                            
                                                                                                  
 conv1_pad (ZeroPadding2D)   (None, 230, 230, 3)          0         ['input_1[0][0]']             
                                                                                                  
 conv1_conv (Conv2D)         (None, 112, 112, 64)         9472      ['conv1_pad[0][0]']           
                                                                                                  
 conv1_bn (BatchNormalizati  (None, 112, 112, 64)         256       ['conv1_conv[0][0]']          
 on)                                                                                       

                                                                                                  
 conv2_block3_1_conv (Conv2  (None, 56, 56, 64)           16448     ['conv2_block2_out[0][0]']    
 D)                                                                                               
                                                                                                  
 conv2_block3_1_bn (BatchNo  (None, 56, 56, 64)           256       ['conv2_block3_1_conv[0][0]'] 
 rmalization)                                                                                     
                                                                                                  
 conv2_block3_1_relu (Activ  (None, 56, 56, 64)           0         ['conv2_block3_1_bn[0][0]']   
 ation)                                                                                           
                                                                                                  
 conv2_blo

 ation)                                                                                           
                                                                                                  
 conv3_block2_3_conv (Conv2  (None, 28, 28, 512)          66048     ['conv3_block2_2_relu[0][0]'] 
 D)                                                                                               
                                                                                                  
 conv3_block2_3_bn (BatchNo  (None, 28, 28, 512)          2048      ['conv3_block2_3_conv[0][0]'] 
 rmalization)                                                                                     
                                                                                                  
 conv3_block2_add (Add)      (None, 28, 28, 512)          0         ['conv3_block1_out[0][0]',    
                                                                     'conv3_block2_3_bn[0][0]']   
          

 conv4_block1_2_conv (Conv2  (None, 14, 14, 256)          590080    ['conv4_block1_1_relu[0][0]'] 
 D)                                                                                               
                                                                                                  
 conv4_block1_2_bn (BatchNo  (None, 14, 14, 256)          1024      ['conv4_block1_2_conv[0][0]'] 
 rmalization)                                                                                     
                                                                                                  
 conv4_block1_2_relu (Activ  (None, 14, 14, 256)          0         ['conv4_block1_2_bn[0][0]']   
 ation)                                                                                           
                                                                                                  
 conv4_block1_0_conv (Conv2  (None, 14, 14, 1024)         525312    ['conv3_block4_out[0][0]']    
 D)       

                                                                                                  
 conv4_block3_out (Activati  (None, 14, 14, 1024)         0         ['conv4_block3_add[0][0]']    
 on)                                                                                              
                                                                                                  
 conv4_block4_1_conv (Conv2  (None, 14, 14, 256)          262400    ['conv4_block3_out[0][0]']    
 D)                                                                                               
                                                                                                  
 conv4_block4_1_bn (BatchNo  (None, 14, 14, 256)          1024      ['conv4_block4_1_conv[0][0]'] 
 rmalization)                                                                                     
                                                                                                  
 conv4_blo

 D)                                                                                               
                                                                                                  
 conv4_block6_3_bn (BatchNo  (None, 14, 14, 1024)         4096      ['conv4_block6_3_conv[0][0]'] 
 rmalization)                                                                                     
                                                                                                  
 conv4_block6_add (Add)      (None, 14, 14, 1024)         0         ['conv4_block5_out[0][0]',    
                                                                     'conv4_block6_3_bn[0][0]']   
                                                                                                  
 conv4_block6_out (Activati  (None, 14, 14, 1024)         0         ['conv4_block6_add[0][0]']    
 on)                                                                                              
          

 conv5_block3_1_relu (Activ  (None, 7, 7, 512)            0         ['conv5_block3_1_bn[0][0]']   
 ation)                                                                                           
                                                                                                  
 conv5_block3_2_conv (Conv2  (None, 7, 7, 512)            2359808   ['conv5_block3_1_relu[0][0]'] 
 D)                                                                                               
                                                                                                  
 conv5_block3_2_bn (BatchNo  (None, 7, 7, 512)            2048      ['conv5_block3_2_conv[0][0]'] 
 rmalization)                                                                                     
                                                                                                  
 conv5_block3_2_relu (Activ  (None, 7, 7, 512)            0         ['conv5_block3_2_bn[0][0]']   
 ation)   

In [4]:
model=tensorflow.keras.Sequential([
    model,
    GlobalMaxPooling2D()
])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 resnet50 (Functional)       (None, 7, 7, 2048)        23587712  
                                                                 
 global_max_pooling2d (Glob  (None, 2048)              0         
 alMaxPooling2D)                                                 
                                                                 
Total params: 23587712 (89.98 MB)
Trainable params: 0 (0.00 Byte)
Non-trainable params: 23587712 (89.98 MB)
_________________________________________________________________


In [14]:
import cv2

path ='1550.jpg'
img = cv2.imread(path)



In [15]:
img=cv2.resize(img,(224,224))

In [16]:
import numpy as np
from numpy.linalg import norm
img =np.array(img)

In [17]:
img.shape

(224, 224, 3)

In [18]:
#(number_of_images,224,224,3)
expand_img=np.expand_dims(img,axis=0)

In [19]:
expand_img.shape

(1, 224, 224, 3)

In [20]:
pre_image=preprocess_input(expand_img)

In [21]:
pre_image.shape

(1, 224, 224, 3)

In [22]:
result=model.predict(pre_image).flatten()

1/1 [==============================] - 4s 4s/step


In [23]:
result

array([3.3281424, 2.8136601, 2.748585 , ..., 4.4833646, 2.9558768,
       2.7638056], dtype=float32)

In [24]:
result.shape

(2048,)

In [25]:
from numpy.linalg import norm
result=result/norm(result)

In [26]:
result

array([0.0109979 , 0.00929778, 0.00908274, ..., 0.01481535, 0.00976774,
       0.00913304], dtype=float32)

In [27]:
def extract_feature(img_path,model):
    img = cv2.imread(img_path)
    img=cv2.resize(img,(224,224))
    img =np.array(img)
    expand_img=np.expand_dims(img,axis=0)
    pre_image=preprocess_input(expand_img)
    result=model.predict(pre_image).flatten()
    normalized=result/norm(result)
    return normalized

In [28]:
extract_feature('1550.jpg',model)

1/1 [==============================] - 0s 288ms/step


array([0.0109979 , 0.00929778, 0.00908274, ..., 0.01481535, 0.00976774,
       0.00913304], dtype=float32)

In [29]:
#path=r'C:\Users\amjat\Desktop\Large Language models\fasion recommendation\try1\images'
import os

In [30]:
path=r'C:\Users\amjat\Desktop\Large Language models\fasion recommendation\try3\allimg'

In [31]:
filename=[]
feature_list=[]

for file in os.listdir(path):
    filename.append(os.path.join(path,file))

In [32]:
len(filename)

2906

In [33]:
filename[:3]

['C:\\Users\\amjat\\Desktop\\Large Language models\\fasion recommendation\\try3\\allimg\\10037.jpg',
 'C:\\Users\\amjat\\Desktop\\Large Language models\\fasion recommendation\\try3\\allimg\\10039.jpg',
 'C:\\Users\\amjat\\Desktop\\Large Language models\\fasion recommendation\\try3\\allimg\\10054.jpg']

In [34]:
from tqdm import tqdm

In [35]:
for file in filename:
    feature_list.append(extract_feature(file,model))

1/1 [==============================] - 0s 233ms/step


1/1 [==============================] - 0s 245ms/step


1/1 [==============================] - 0s 227ms/step


1/1 [==============================] - 0s 235ms/step


1/1 [==============================] - 0s 222ms/step


1/1 [==============================] - 0s 275ms/step


1/1 [==============================] - 0s 227ms/step


1/1 [==============================] - 0s 234ms/step


1/1 [==============================] - 0s 232ms/step


1/1 [==============================] - 0s 226ms/step


1/1 [==============================] - 0s 232ms/step


1/1 [==============================] - 0s 233ms/step


1/1 [==============================] - 0s 231ms/step


1/1 [==============================] - 0s 235ms/step


1/1 [==============================] - 0s 276ms/step


1/1 [==============================] - 0s 233ms/step


1/1 [==============================] - 0s 278ms/step


1/1 [==============================] - 0s 252ms/step


1/1 [==============================] - 0s 178ms/step


In [36]:
import pickle
pickle.dump(feature_list,open('featurevector.pkl','wb'))
pickle.dump(filename,open('filenames.pkl','wb'))

In [46]:
class Solution:
    def getWinner(self, arr, k: int) -> int:
        count=0
        current=0
        while count<k:
            if arr[0]>arr[1]:
                current=arr[0]
                ele=arr.pop(1)
                arr.append(ele)
                if current==arr[0]:
                    count+=1
            else:
                current=arr[1]
                ele=arr.pop(0)
                arr.append(ele)
                if current==arr[1]:
                    count+=1
        return arr[0]

In [48]:
# arr = [2,1,3,5,4,6,7]
# k = 2
arr=[3,2,1]
k = 10
obj=Solution()
obj.getWinner(arr,k)

3

In [54]:
class Solution:
    def isPathCrossing(self, path: str) -> bool:

        origin=[0,0]
        for i in path:
            if i=='N':
                origin[0]+=1
            elif i=='S':
                origin[0]-=1
            elif i=='E':
                origin[1]+=1
            elif i=='W':
                origin[1]-=1
            if origin==[0,0]:
                return True
            print(origin)
        else:
            return False



In [56]:
path = "NESWW"
obj=Solution()
obj.isPathCrossing(path)

[1, 0]
[1, -1]
[0, -1]


True